### ISSUE TITLE
Pivotal Tracker links in release notes are not publicly viewable

### ISSUE THREAD

**Issue by hodnett** [cloudfoundry/staticfile-buildpack#180]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

N/A

What version of the buildpack you are using?

Issue impacts Github release notes for versions 1.5.4 (at least) through 1.5.9.

If you were attempting to accomplish a task, what was it you were attempting to do?

View the "story" behind adding new Nginx versions, and whether various issues were addressed, such as the "inability to switch Nginx versions" documented in https://github.com/cloudfoundry/staticfile-buildpack/issues/179#issue-672378482.

What did you expect to happen?

I expected to view the story, much as I am able to view tracker links added as comments to issues.

What was the actual behavior?

I receive an error:

"Sorry, we couldn't find that story. It may be in a private project or may have been deleted. Try signing in to view."

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by kvedurmu** [comment]
Hi @hodnett that tracker instance is publicly viewable so weird that you're seeing this issue. The CF buildpacks maintainers have actually moved over recently to an entirely Github based issue workflow, so we will look into removing this cf-github integration from all of our repos. So, this means there's not really a need to follow the tracker story itself as we're posting comments/clarifications in the issue itself. Closing this out for now, and we'll get around to triaging the actual issue you reported fairly soon. Thanks.
